# Generated by Django 6.0.5 on 2026-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("YET_TO_START", "Yet To Start"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ON_HOLD", "On Hold"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                default="YET_TO_START",
                max_length=20,
            ),
        ),
    ]
