# Generated by Django 6.0.5 on 2026-05-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_task_description_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Yet To Start", "Yet To Start"),
                    ("In Progress", "In Progress"),
                    ("On Hold", "On Hold"),
                    ("Under Review", "Under Review"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="YET_TO_START",
                max_length=20,
            ),
        ),
    ]
