# Generated by Django 6.0.5 on 2026-05-17 09:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_created_at_report_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
